// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.4
// source: dm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*SessionRequest_Start
	//	*SessionRequest_Heartbeat
	Request isSessionRequest_Request `protobuf_oneof:"request"`
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{0}
}

func (m *SessionRequest) GetRequest() isSessionRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SessionRequest) GetStart() *SessionRequest_StartSessionRequest {
	if x, ok := x.GetRequest().(*SessionRequest_Start); ok {
		return x.Start
	}
	return nil
}

func (x *SessionRequest) GetHeartbeat() *SessionRequest_HeartbeatRequest {
	if x, ok := x.GetRequest().(*SessionRequest_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isSessionRequest_Request interface {
	isSessionRequest_Request()
}

type SessionRequest_Start struct {
	Start *SessionRequest_StartSessionRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type SessionRequest_Heartbeat struct {
	Heartbeat *SessionRequest_HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*SessionRequest_Start) isSessionRequest_Request() {}

func (*SessionRequest_Heartbeat) isSessionRequest_Request() {}

type SessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*SessionResponse_Start
	//	*SessionResponse_Heartbeat
	Response isSessionResponse_Response `protobuf_oneof:"response"`
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{1}
}

func (m *SessionResponse) GetResponse() isSessionResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *SessionResponse) GetStart() *SessionResponse_StartSessionResponse {
	if x, ok := x.GetResponse().(*SessionResponse_Start); ok {
		return x.Start
	}
	return nil
}

func (x *SessionResponse) GetHeartbeat() *SessionResponse_HeartbeatResponse {
	if x, ok := x.GetResponse().(*SessionResponse_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isSessionResponse_Response interface {
	isSessionResponse_Response()
}

type SessionResponse_Start struct {
	Start *SessionResponse_StartSessionResponse `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type SessionResponse_Heartbeat struct {
	Heartbeat *SessionResponse_HeartbeatResponse `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*SessionResponse_Start) isSessionResponse_Response() {}

func (*SessionResponse_Heartbeat) isSessionResponse_Response() {}

type SessionRequest_StartSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomToken string `protobuf:"bytes,1,opt,name=room_token,json=roomToken,proto3" json:"room_token,omitempty"`
}

func (x *SessionRequest_StartSessionRequest) Reset() {
	*x = SessionRequest_StartSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRequest_StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest_StartSessionRequest) ProtoMessage() {}

func (x *SessionRequest_StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest_StartSessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest_StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SessionRequest_StartSessionRequest) GetRoomToken() string {
	if x != nil {
		return x.RoomToken
	}
	return ""
}

type SessionRequest_HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionRequest_HeartbeatRequest) Reset() {
	*x = SessionRequest_HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRequest_HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest_HeartbeatRequest) ProtoMessage() {}

func (x *SessionRequest_HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest_HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest_HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{0, 1}
}

type SessionResponse_StartSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartApp []byte `protobuf:"bytes,1,opt,name=startApp,proto3" json:"startApp,omitempty"`
}

func (x *SessionResponse_StartSessionResponse) Reset() {
	*x = SessionResponse_StartSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionResponse_StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse_StartSessionResponse) ProtoMessage() {}

func (x *SessionResponse_StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse_StartSessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse_StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SessionResponse_StartSessionResponse) GetStartApp() []byte {
	if x != nil {
		return x.StartApp
	}
	return nil
}

type SessionResponse_HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SessionResponse_HeartbeatResponse) Reset() {
	*x = SessionResponse_HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionResponse_HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse_HeartbeatResponse) ProtoMessage() {}

func (x *SessionResponse_HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse_HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse_HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_dm_proto_rawDescGZIP(), []int{1, 1}
}

var File_dm_proto protoreflect.FileDescriptor

var file_dm_proto_rawDesc = []byte{
	0x0a, 0x08, 0x64, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x64, 0x6d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x88, 0x02,
	0x0a, 0x0e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x4d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x35, 0x2e, 0x64, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6c, 0x69, 0x76, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x52, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x32, 0x2e, 0x64, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6c,
	0x69, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x1a, 0x34, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x12, 0x0a, 0x10, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x6d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x54, 0x0a,
	0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x34, 0x2e, 0x64, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6c, 0x69, 0x76,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x1a, 0x32, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x70, 0x70, 0x1a, 0x13, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x63, 0x0a, 0x09, 0x44, 0x4d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x21, 0x2e, 0x64, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x6c, 0x69, 0x76,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62,
	0x6c, 0x69, 0x76, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1e, 0x5a,
	0x1c, 0x68, 0x75, 0x62, 0x65, 0x72, 0x74, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x73, 0x74, 0x2d, 0x64, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dm_proto_rawDescOnce sync.Once
	file_dm_proto_rawDescData = file_dm_proto_rawDesc
)

func file_dm_proto_rawDescGZIP() []byte {
	file_dm_proto_rawDescOnce.Do(func() {
		file_dm_proto_rawDescData = protoimpl.X.CompressGZIP(file_dm_proto_rawDescData)
	})
	return file_dm_proto_rawDescData
}

var file_dm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dm_proto_goTypes = []interface{}{
	(*SessionRequest)(nil),                       // 0: dmserver.blive.v1.SessionRequest
	(*SessionResponse)(nil),                      // 1: dmserver.blive.v1.SessionResponse
	(*SessionRequest_StartSessionRequest)(nil),   // 2: dmserver.blive.v1.SessionRequest.StartSessionRequest
	(*SessionRequest_HeartbeatRequest)(nil),      // 3: dmserver.blive.v1.SessionRequest.HeartbeatRequest
	(*SessionResponse_StartSessionResponse)(nil), // 4: dmserver.blive.v1.SessionResponse.StartSessionResponse
	(*SessionResponse_HeartbeatResponse)(nil),    // 5: dmserver.blive.v1.SessionResponse.HeartbeatResponse
}
var file_dm_proto_depIdxs = []int32{
	2, // 0: dmserver.blive.v1.SessionRequest.start:type_name -> dmserver.blive.v1.SessionRequest.StartSessionRequest
	3, // 1: dmserver.blive.v1.SessionRequest.heartbeat:type_name -> dmserver.blive.v1.SessionRequest.HeartbeatRequest
	4, // 2: dmserver.blive.v1.SessionResponse.start:type_name -> dmserver.blive.v1.SessionResponse.StartSessionResponse
	5, // 3: dmserver.blive.v1.SessionResponse.heartbeat:type_name -> dmserver.blive.v1.SessionResponse.HeartbeatResponse
	0, // 4: dmserver.blive.v1.DMService.Session:input_type -> dmserver.blive.v1.SessionRequest
	1, // 5: dmserver.blive.v1.DMService.Session:output_type -> dmserver.blive.v1.SessionResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dm_proto_init() }
func file_dm_proto_init() {
	if File_dm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRequest_StartSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionRequest_HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionResponse_StartSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionResponse_HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dm_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SessionRequest_Start)(nil),
		(*SessionRequest_Heartbeat)(nil),
	}
	file_dm_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SessionResponse_Start)(nil),
		(*SessionResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dm_proto_goTypes,
		DependencyIndexes: file_dm_proto_depIdxs,
		MessageInfos:      file_dm_proto_msgTypes,
	}.Build()
	File_dm_proto = out.File
	file_dm_proto_rawDesc = nil
	file_dm_proto_goTypes = nil
	file_dm_proto_depIdxs = nil
}
