# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: macos-14
            asset_name: dmj-macos-arm64
          - image: ubuntu-22.04
            depends: libgtk-3-dev libwebkit2gtk-4.0-dev
            asset_name: dmj-linux-amd64
          - image: windows-2022
            extra_ldflags: -H windowsgui
            asset_name: dmj-windows-amd64.exe
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.depends }}
      - name: Build
        run: go build -v ./...
      - name: Build Release Binary
        run: go build --ldflags "-s -w ${{ matrix.extra_ldflags }}" -o "${{ matrix.asset_name }}" ./cmd/ui
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}
          retention-days: 5
